neurostuff/NiMARE

nimare/meta/ibma/ibma.py

Based on discussion in #8, IBMAs can be either one- or two-tailed, the FFX GLM can be done with FSL, and SE maps from NIDM results should be squared before being used by FSL.

Add tail argument to IBMAs and use FSL for FFX GLM

---

nimare/version.py

abc is a part of the standard library and does not need to be installed (Thanks to @bilgelm)

[FIX] remove abc as dependency

---

nimare/base/meta.py
nimare/meta/cbma/ale.py
nimare/meta/cbma/mkda.py

This PR tweaks the `MetaResult` class to add a reference to the originating `Estimator` instance. This will be important when writing out logs—we'll want to include the estimator's name, parameters, etc. Closes #45.

store originating estimator in MetaResult

---

nimare/meta/cbma/ale.py

Pass n_cores to run_ale and if n_cores == 1, then don't use a multiproc pool
closes #78

ADD when ALE is called with 1 core, don't use a pool

---

nimare/cli.py
nimare/workflows/ibma_perm.py

```
Usage: nimare conperm [OPTIONS] CONTRAST_IMAGES...
Metaanalysis of contrast maps using random effects and two-sided inference
with empirical (permutation based) null distribution and Family Wise Error
multiple comparison correction.
Options:
--output_dir TEXT     Where to put the output maps.
--output_prefix TEXT  Common prefix for output maps.  [default: ]
--n_iters INTEGER     Number of iterations for permutation testing.
[default: 10000]
--help                Show this message and exit.
```

adding the `conperm` CLI command

---

nimare/meta/cbma/kernel.py
nimare/meta/cbma/utils.py

Using groupby instead of looping through ids and calling loc is a little bit faster. Using the '.' accessor is slightly faster than using the '[]' to get values. Also, I added some small optimizations in the compute_ma code.

Small speedups in kernel transforms

---

nimare/correct/__init__.py
nimare/correct/base.py

This PR creates a skeleton `nimare.correct` hierarchy with a barebones class hierarchy, to illustrate how the API could work. This is untested and may need some tweaking. I added a sample `FDRCorrect` class to illustrate usage.

skeleton of MC correction hierarchy

---

nimare/base/base.py

Closes None.
- Scikit-learn no longer has a custom signature function, which has been raising errors in our tests. I've updated our base class's parameter inspection methods to match scikit-learn's current version.

[FIX] Remove deprecated sklearn dependency

---

nimare/io.py

Closes #129.
- Makes the Sleuth converter more flexible, to allow for multiline experiment names. These occur when the name is too long and ends up wrapped in the text file, or when grouping is applied to consolidate experiments within the same study.

[FIX] Support multiline experiment names in Sleuth converter

---

nimare/tests/conftest.py

When the tests are first run, the NIDM pain dataset will be saved locally under `~.nidm`, preventing a ~200 MB download each time.
Closes #172.

Save pain test dataset to local directory

---

.zenodo.json
nimare/correct/correct.py

Closes #181.
I added the missing parameter `q` in the `__init__`function of the `nimare.correct.FDRCorrector`.
The other alternative would have been to read this parameter from the existing `self.parameters` dictionary but I found it weirder since `q` is a required argument.

[FIX] Fix missing parameter q of FDRCorrector

---

.circleci/artifact_path
.circleci/config.yml
README.md
docs/requirements-dev.txt
nimare/info.py

Closes #180. Takes approach from pybids and fmriprep.
- Add step in CircleCI config for building docs.
- Add artifact_path file with path to doc main page.

[TST] Add CI step for building docs

---

nimare/cli.py
nimare/correct/base.py
nimare/meta/cbma/ale.py
nimare/workflows/ale.py

Closes None. Addresses a bug identified by @mriedel56 offline, in which ALESubtractions were not returning any maps in the MetaResults objects.
- Was setting self.results within the _fit method, and returning None. The problem is that _fit is supposed to return the images dictionary, and fit is what sets self.results. So it was overwriting self.results with an empty MetaResult object.
- Add n_cores defaults to CLI.

[FIX] Retain ALESubtraction results

---

nimare/meta/cbma/ale.py
nimare/meta/cbma/mkda.py
nimare/parcellate/mamp.py

Closes None. References #195. Pending #163.
- Change CBMAEstimators' `kernel_estimator` attribute to `kernel_transformer`.

[REF] Rename kernel_estimator attribute to kernel_transformer

---

docs/api.rst
docs/conf.py
nimare/base.py

Closes None.
- Clean up conf.py, removing unused extensions and variables.
- Add annotate sub-submodules to API file. They're nested in the annotate submodules, and the module.rst template can't document submodules for some reason.

[DOC] Fix annotate API docs

---

nimare/meta/cbma/ale.py
nimare/transforms.py

Closes #253.
- Preallocate arrays with ones instead of zeros.
- Other estimators should be fine since they determine p-values and transform to -log(p) in the same step.

[FIX] Preallocate ALE cFWE p-value array with ones instead of zeros

---

nimare/base.py
nimare/meta/cbma/ale.py
nimare/meta/cbma/mkda.py
nimare/tests/test_cbma_mkda.py

Closes None.
- Allow kernel transformers to be initialized before they're fed into the meta-analytic estimator.
- Pop a few things up in the CBMAEstimator hierarchy to reduce duplication.

[ENH] Support initialized and uninitialized kernels for CBMA

---

nimare/utils.py

Closes None, but fixes a bug I noticed while working on #273.
- In Dataset DataFrame attributes, fill missing values with `None` instead of `numpy.nan`. This works with `Dataset.get` and other methods that were checking against None rather than `isnan`. It also makes it easier to have missing data in the json file.

[FIX] Replace NaNs in Datasets with Nones

---

nimare/annotate/cogat.py
nimare/tests/test_annotate_cogat.py

Closes None, but fixes a bug identified by @julio-a-yanes.
- Copy `texts` DataFrame in `nimare.annotate.cogat.extract_cogat()` _before_ operating on the DataFrame. This was dropping the `id` column from the `Dataset.texts` attribute, which prevented Dataset slicing.
- Add check in cogat test for this bug.

[FIX] Operate on copy of df in extract_cogat()

---

nimare/io.py
nimare/meta/ale.py
nimare/tests/test_annotate_cogat.py

Closes None. On a test dataset (used as both dset 1 and dset 2) with 21 studies and with 100 iterations, it drops memory from 1039.6 MiB to 602.8 MiB. This difference probably doesn't scale well with larger numbers of iterations, since the null distribution arrays will increasingly dominate memory consumption as the number of iterations increases.
- Switch from creating MA maps as images and masking them to get arrays to just creating the maps as arrays to begin with.

[REF] Operate on arrays in ALESubtraction

---

nimare/io.py
nimare/tests/data/test_sleuth_file2.txt
nimare/tests/data/test_sleuth_file3.txt
nimare/tests/data/test_sleuth_file4.txt
nimare/tests/data/test_sleuth_file5.txt
nimare/tests/test_io.py
nimare/transforms.py

Closes None. Fixes gaps in the docstrings for functions identified by @mriedel56.
- Test `convert_sleuth_to_dataset` with multiple Sleuth files.
- Explicitly support multiple input files in docstrings for `convert_sleuth_to_dataset`, `convert_sleuth_to_json`, and `convert_sleuth_to_dict`.
- Clean up how those multiple input files are handled.
-  Improve documentation of `mni2tal` and `tal2mni` functions.

[DOC] Fix Lancaster xform and Sleuth conversion docstrings

---

nimare/base.py
nimare/meta/ale.py
nimare/meta/mkda.py
nimare/tests/test_meta_ale.py
nimare/workflows/ale.py

Closes #246. References #189.
- Add a `PairwiseCBMAEstimator` base class.
- Add a low_memory option to ALESubtraction.
- Use `numpy.memmap` for the largest array in the method (the voxel-wise null distributions of difference scores).

[ENH] Add PairwiseCBMAEstimator class and add low_memory option to ALESubtraction

---

examples/02_meta-analyses/plot_generate_ma_maps.py
nimare/base.py
nimare/dataset.py
nimare/meta/kernel.py
nimare/meta/mkda.py
nimare/stats.py
nimare/tests/test_meta_kernel.py

Closes #41 and closes #307 and references #195.
- Add copy method to Dataset so that kernel transformers, when returning Datasets, don't update the original object.
- Track image basepath in Dataset.
- Support Dataset transformation in kernel transformers. This transformation creates an unmasked version of the MA map, saves it to a file based on `Dataset.basepath` and the parameters of the transformer, and stores the path in the `Dataset.images` attribute.
- Fix bug in `nimare.stats.null_to_p()`. Values outside the range of the null distribution (i.e., p = 0) are now cropped down to epsilon for float.
To do:
Something to perhaps keep an eye on is that there was a new overflow error in one of the MKDA tests. Since these changes shouldn't impact …

[ENH] Support Dataset transformations in kernel transformers

---

nimare/info.py
nimare/tests/test_meta_kernel.py
nimare/tests/test_meta_mkda.py

Closes None. I don't think this should be necessary, but RTD is failing with the following error:
```
Processing /home/docs/checkouts/readthedocs.org/user_builds/nimare/checkouts/latest
Installing build dependencies: started
Installing build dependencies: finished with status 'done'
Getting requirements to build wheel: started
Getting requirements to build wheel: finished with status 'done'
ERROR: Exception:
Traceback (most recent call last):
File "/home/docs/checkouts/readthedocs.org/user_builds/nimare/envs/latest/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 216, in _main
status = self.run(options, args)
File "/home/docs/checkouts/readthedocs.org/user_builds/nimare/envs/latest/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 182, in wrapper …
```

[FIX] Add setuptools to requirements

---

docs/index.rst
docs/outputs.rst
nimare/meta/ale.py
nimare/meta/mkda.py

Closes None, but references #133.
- Change natural logarithms in ALE and MKDA modules to base-ten logarithms to match NiMARE's broader convention.
- Create `docs/outputs.rst` to document output naming convention.
- Reorder items in documentation sidebar to better reflect their importance. Namely, the CLI is a useful item, but most users should use the Python functions directly, so the API should be at the top of the sidebar, and CLI should be at the bottom.

[FIX, DOC] Change natural log to base-ten and document output naming convention

---

nimare/resources/filenames.json

Closes #133. Note that this configuration file is _not used_ for anything just yet.
- Add json describing filename convention based on `pybids`' configuration file.

[INFRA] Add json describing filename convention

---

nimare/stats.py
nimare/tests/test_stats.py

Closes #364 
- p-values are clipped in null_to_p such that they have to be in the range [smallest_value, (1 - smallest_value)]
- added test to check behavior.
[the solution came from stackoverflow](https://stackoverflow.com/questions/4092528/how-to-clamp-an-integer-to-some-range)

[FIX] enforce correct lowest p-value

---

nimare/base.py
nimare/meta/kernel.py

The `KernelTransformer` hierarchy had a lot of redundancy, so I refactored it. Mostly I've pushed a lot of code into the base class's `transform()` method, which now internally calls an `_apply_kernel()` class method that needs to be implemented in subclasses. I stopped short of making this an abstract method, as the `Peaks2MapKernel` looks like it does something a little different, and I haven't taken the time yet to shoehorn it into the structure of the other kernel classes. But I don't think there's really a good use case for that kernel at the moment, so I'm not very concerned about it (TBH I wonder if we should just remove it entirely—it would be kind of disastrous if people started to use it in meta-analyses).
Tests seem to pass, but I haven't added any new ones, as there's no new …

[REF] Refactor KernelTransformer hierarchy

---

examples/02_meta-analyses/plot_cbma.py
examples/02_meta-analyses/plot_cbma_combine_estimators_and_kernels.py
nimare/meta/ale.py
nimare/meta/mkda.py
nimare/tests/test_decode_continuous.py
nimare/tests/test_estimator_performance.py
nimare/tests/test_meta_ale.py
nimare/tests/test_meta_mkda.py

Closes #371, closes #348, closes #349.
TODO:
- Validate method. I'm thinking a close code review and an example should be sufficient.
- Add an empirical null-based approach to the ALE, MKDADensity, and KDA Estimators.
- Add tests for empirical null method.
- Simplify ALE calculation (I'm kicking myself over this).

[ENH] Add empirical null method to density-based CBMA Estimators

---

nimare/base.py
nimare/meta/kernel.py
nimare/meta/mkda.py
nimare/tests/test_meta_mkda.py

Closes #370. This must be merged _after_ #372. This *does not* implement the null method for KDA, since it's very difficult to determine the maximum possible OF value for KDA meta-analyses when preallocating the histogram bins.
- Add `_compute_null_analytic()` method to MKDADensity.
- Add test for MKDADensity with the analytic null.
- Add `_compute_summarystat()` method to MKDADensity. This is duplicated in #372.
- Add `_compute_null_empirical()` method to MKDADensity. This was a commit mistake, and this method should be reviewed in #372.
- Add `_summarystat_to_p()` method to MKDADensity. Also a duplicate of #372.

[ENH] Add analytic null method to MKDADensity

---

nimare/tests/test_dataset.py
nimare/utils.py

Closes #405
- return empty dataframe for coordinates to pass data validation during dataset creation.
- add test for empty dataset
I'm not sure if we want to allow an empty dataset object or explicitly test that at least one of either coordinates or images be set for this to be a valid "dataset" object.

[FIX] Allow no coordinates in a dataset

---

nimare/dataset.py

Closes None. I am working through the listings for the NiMARE manuscript, and I noticed that the MA maps for the first study in a Sleuth dataset didn't match up with the actual coordinates for that study.
I think there will still be an odd mismatch when there aren't coordinates for all studies in a Dataset, but I don't know what to do about that at the moment.
- Sort `Dataset.ids` and rows of all DataFrame-based Dataset attributes based on the `id` column whenever they're set.

[FIX] Sort all arrays and DataFrames in Dataset by ID

---

nimare/meta/cbma/ale.py
nimare/meta/cbma/mkda.py

Closes #412.
- Add logging warning to beginning of each Estimator's initialization if kernel doesn't match default.

[DOC] Add warnings for kernel/estimator mismatch

---

nimare/meta/cbma/ale.py
nimare/meta/cbma/base.py

Closes #396.
- Increase resolution of ALE analytic null histogram from bins of 0.0001 to bins of 0.00001.
- Round up maximum MA values based on target resolution in ALE histogram generation so that we don't need an arbitrary buffer.
- This involves including one extra bin in the histogram that has an impossible value (e.g., 1.000001). See https://github.com/neurostuff/NiMARE/pull/411#issuecomment-736996415 for rationale.
- Simplify histogram generation in ALE.
- This involves cropping histogram bins when shifting from edges to centers.
- ~~Also increase resolution of SCALE analytic null histogram by same factor.~~ Reverted since it was too memory-intensive for the CI.

[ENH] Improve convergence between ALE null methods

---

nimare/extract/extract.py
nimare/extract/utils.py
nimare/generate.py
nimare/meta/cbma/ale.py
nimare/meta/kernel.py
nimare/meta/utils.py
nimare/tests/test_estimator_performance.py

Closes #347.
- Restructure `Peaks2MapsKernel` to follow the `KernelTransformer` convention.
- Rename `compute_ma` to `compute_ale_ma` to match convention.
- Rename `peaks2maps` to `compute_p2m_ma` to match convention.
- Do not test `Peaks2MapsKernel` in `test_estimator_performance.py` (see #417).

[FIX] Restructure Peaks2MapsKernel to operate like other kernels

---

nimare/tests/test_meta_kernel.py

Closes #367 and supersedes #368 (if it works).
- Allow Peaks2Maps test to download the model to the NiMARE resources folder instead of a temporary directory.
- This will keep the test from downloading the model every time it's run locally.
- Add new test for P2M + MKDA.

[TST] Do not download test peaks2maps to tmpdir

---

.circleci/config.yml
docs/api.rst
nimare/meta/cbma/ale.py
nimare/meta/cbma/base.py
nimare/meta/cbma/mkda.py
nimare/stats.py
nimare/tests/test_estimator_performance.py
nimare/tests/test_stats.py

Closes #403. 
- Add `nimare.stats.nullhist_to_p()` function for converting test statistics to p-values using a null distribution stored in a histogram.
- Use `nimare.stats.nullhist_to_p()` in CBMA estimators.
- Crop out-of-bounds p-values to ~~epsilon~~ smallest observed non-zero p-value.
TODO:

[FIX] Add nullhist_to_p and crop invalid p-values

---

nimare/meta/cbma/ale.py
nimare/meta/cbma/mkda.py

Closes None, but fixes a documentation bug I introduced in #416.
- Check kernel transformer as both an instance and a class. Before it just checked for instances.

[FIX] Fix the warnings about mismatched kernels and estimators

---

nimare/meta/cbma/mkda.py
nimare/meta/kernel.py

Closes #417, in that we will not test Peaks2MapsKernel in conjunction with any meta-analytic estimators, so any issues with memory usage can be ignored.
- Add warning to docstring and log warning at initialization of Peaks2MapsKernel, to clarify to users that they should **not** use the kernel for any serious research.
- Add warning to docstring and log warning at initialization of KDA estimator, to make it clear that the KDA estimator is inferior to MKDA and should not be used for real meta-analyses.

[DOC] Warn users about Peaks2MapsKernel and KDA Estimator

---

nimare/meta/cbma/base.py

Closes #429. Essentially, in #409, I changed the internal storage of the analytic null from a null distribution (i.e., normalized reversed cumulatively summed histogram weights) to the raw histogram weights, with the conversion to a null distribution happening in `stats.nullhist_to_p()`. However, I neglected to _also_ update `CBMAEstimator._p_to_summarystat()`, which uses the same attribute.
As a result, cFWE-corrected maps were empty.
- Convert the analytic null histogram weights to a null distribution before calculating the appropriate summary statistic in `CBMAEstimator._p_to_summarystat()`.

[FIX] Convert histogram weights to null distribution in p-to-stat conversion

---

examples/02_meta-analyses/plot_cbma.py
examples/02_meta-analyses/plot_cbma_combine_estimators_and_kernels.py
nimare/meta/cbma/ale.py
nimare/meta/cbma/base.py
nimare/meta/cbma/mkda.py
nimare/tests/test_decode_continuous.py
nimare/tests/test_estimator_performance.py
nimare/tests/test_meta_ale.py
nimare/tests/test_meta_mkda.py

Closes #389.
- Add `_determine_histogram_bins()` method to CBMA Estimators. This method determines the bins for the analytic null and the full empirical null, but not the basic (single-coordinate) empirical null, which doesn't use a histogram.
- Add `_run_montecarlo_permutation()` and `_compute_null_reduced_empirical()` methods to base CBMAEstimator.
- Edit `_compute_null_empirical()` to run full coordinate-set method.
- Add `vfwe_only` parameter to the standard Monte Carlo permutation method for FWE correction.
- Directly infer the weighting factor for the kernel in the KDA estimator instead of trying to guess it from MA values.
- This is currently incompatible with continuous kernels, but I may change that before merging this PR.

[ENH] Implement full coordinate-set empirical null method 

---

nimare/base.py
nimare/tests/conftest.py
nimare/tests/test_meta_ibma.py

Closes #438
- check if resampling is necessary (and raise error if resampling is not requested)
- add resampling kwargs for user flexibility
- TODO: decide where to pass resampling arguments (should they be passed through the `fit` method or should we make it a part of initializing the estimator object so the user's decision is saved in a more permanent way? and to keep the `fit` method clean)

[FIX,REF] start changing how to handle resampling

---

nimare/meta/cbma/ale.py
nimare/stats.py
nimare/tests/test_stats.py

Fixes the issue identified in #442, which turned out to stem from a bug in `stats.null_to_p`. I replaced the previous call to `scipy.stats.percentileofscore` with an alternative approach that relies on `np.searchsorted`; this approach has the benefit of being vectorized, so it should be much faster in cases where the null distribution is IID across voxels (though it won't help, and might even slow things down slightly, in cases where we need to loop in order to generate a different null distribution for each voxel).
I also updated/improved the tests to make sure they cover common use cases.
Closes #442.

[FIX] Permutation p-values

---

nimare/decode/continuous.py
nimare/meta/kernel.py
nimare/meta/utils.py
nimare/tests/test_estimator_performance.py
nimare/tests/test_meta_ale.py
nimare/tests/test_meta_kernel.py

Closes #452.
- Add low_memory option for kernel transformers that uses numpy.memmap.
- Use low_memory option in CorrelationDecoder.

[ENH] Add low-memory option for kernel transformers

---

nimare/results.py
nimare/tests/test_meta_ibma.py

Closes #454.
upstream fix nilearn/nilearn#2725
- treat input as 2D for maskers that do not support 1D inputs and squeeze the result
- ensure the dimensions are correct in test

[FIX] Add work-around for maskers that do not accept 1D input

---

nimare/io.py
nimare/tests/test_io.py

Closes #456 .
- add collection_id and image_id to filename to prevent name collisions when downloading the data 
- add test to ensure failing case now works

[FIX] Neurovault name collisions

---

nimare/base.py
nimare/meta/cbma/ale.py
nimare/meta/cbma/base.py
nimare/meta/cbma/mkda.py
nimare/tests/test_meta_ale.py

Closes #461.
- Add a new `inputs_` field called `ma_maps` in which MA maps stored in the Dataset's images attribute are collected, should they exist.

[REF] Use saved MA maps, when available, in CBMA estimators

---

nimare/meta/cbma/ale.py
nimare/meta/cbma/base.py
nimare/meta/kernel.py
nimare/meta/utils.py
nimare/tests/test_meta_ale.py
nimare/utils.py

Closes None. In working on the NiMARE paper, I've had trouble with memory issues. At minimum, writing temporary files (created when the `low_memory` option is used) to the NiMARE data directory will make it easier for users to track the files and remove them as necessary.
- Write temporary files created in `ALEKernel`, `MKDAKernel`, `KDAKernel`, and `ALESubtraction` to the NiMARE data directory instead of temporary directories.
- Log the temporary filenames. I'd love to log their sizes as well, but I'm not sure how to estimate the file size before it's created. It should just be a matter of the data type and the size though...

[REF] Write temporary files to the NiMARE data directory

---

nimare/meta/cbma/ale.py

Closes None, but addresses an issue reported by @mriedel56 offline.
- Change `symmetric=True` to `symmetric=False`.
- Add comment about use of `symmetric=False` to code.
- Output p-value map for ALESubtraction in addition to z-value map.

[FIX] Assume non-symmetric null distribution in ALESubtraction

---

nimare/tests/test_utils.py
nimare/utils.py

Closes #471. While we should still revisit how images are validated and paths to images are stored, this at least should fix the immediate issue.
- Refactor and clean up find_stem, so that it finds the common _stem_ (or beginning substring) instead of the largest common substring in any part of the set of strings.
- Add test for find_stem.

[FIX] Find common stem in find_stem instead of largest common substring

---

nimare/dataset.py

Closes #473.
- Within `Dataset.update_path()`, replace the assigned path with the absolute path.

[FIX] Set Dataset.basepath using absolute path

---

nimare/transforms.py

Closes None. This partially addresses the problem identified in https://github.com/neurostuff/PyMARE/issues/61. 
Specifically, PyMARE was only responsible for some of the NaNs in the meta-analysis results (see picture below). A big part of the problem was that study 2621, which has a t-statistic map on Neurovault, has a very large sample size (1385) and very high t-statistics (max is ~85). When fed through [`nimare.transforms.t_to_z()`](https://nimare.readthedocs.io/en/latest/generated/nimare.transforms.t_to_z.html#nimare.transforms.t_to_z), the resulting z-values for those very-significant t-statistics became NaNs. Therefore, I think we need to crop extreme p-values (from t-statistic + dof --> p-value conversion) to epsilon before transforming _those_ to z-values.
Changes proposed in …

[FIX] Deal with extreme t-values in t_to_z by truncating associated p-values

---

nimare/meta/ibma.py
nimare/tests/test_meta_ibma.py

Closes #466. The actual investigation into the effect of aggregation on IBMA results can continue in #475.
- Raise ValueError at `fit()` of Fishers and Stouffers Estimators if the masker is not a NiftiMasker.
- Log warning at `fit()` of WeightedLeastSquares, DerSimonianLaird, Hedges, and VarianceBasedLikelihood Estimators if the masker is not a NiftiMasker.
- Add test that checks for expected behavior of each Estimator when supplied a NiftiLabelsMasker.
- Add information about valid masking approaches to docstrings of affected Estimators.

[ENH] Incorporate information about valid masking approaches into IBMA Estimators

---

nimare/io.py
nimare/tests/test_io.py

Closes None, but is related to #522.
- Allow dictionaries of feature group-file mappings for annotation_file input to Neurosynth conversion functions. This will let us accept multiple feature types, which is especially useful for NeuroQuery.
- Add a test.

[ENH] Accept multiple annotations files in Neurosynth converter

---

docs/conf.py

I don't want to see `__repr__` listed under each class's methods.

[DOC] Change napoleon settings

---

nimare/meta/kernel.py
nimare/tests/test_meta_kernel.py

Closes #547.
- Extract sample size information from Dataset metadata and add to coordinates DataFrame within `KernelTransformer.transform()`.
- I've included a check to ensure that this won't be run if the column already exists in the DataFrame.
- This fix should only affect `ALEKernel` when run on a `Dataset` instead of a `pandas.DataFrame`, which should only happen when you're called it directly. The CBMAEstimators feed in `pandas.DataFrame`s.
- Test this new behavior.
- Miscellaneous cleanup for kernel module.

[FIX] Extract relevant metadata in kernel transformers for Dataset-based transform calls

---

examples/02_meta-analyses/plot_compare_ibma_and_cbma.py
examples/02_meta-analyses/plot_ibma.py

Closes #543. Basically, this PR uses `resample` when running image-based meta-analyses on the NIDM 21 pain dataset, because that dataset is in MNI space with a 2mm3 resolution and 91x109x91 matrices, but the only MNI brain in `nilearn` from >=0.8.1 has differently-sized matrices.
We still end up with a bunch of warnings because any masking applied to the pain dataset images will now involve resampling, and those images all have NaNs outside their brain coverage, which `nilearn` doesn't like.
- Use `resample=True` for all IBMA estimators in examples when running IBMAs on the NIDM 21-pain dataset.

[FIX] Use `resample=True` in IBMA examples

---

nimare/decode/continuous.py

Closes #559.
- When referencing the list of features used in the decoder, use `self.features_` (the final set) instead of `self.features` (the initial set, which may be `None`).

[FIX] Reference selected features instead of initial features in CorrelationDecoder

---

examples/02_meta-analyses/macm.py
nimare/base.py
nimare/dataset.py
nimare/info.py
nimare/meta/cbma/ale.py
nimare/meta/cbma/base.py
nimare/meta/cbma/mkda.py
nimare/meta/kernel.py
nimare/tests/test_dataset.py
nimare/tests/test_meta_ale.py
nimare/tests/test_meta_kernel.py
nimare/utils.py
nimare/workflows/scale.py

Closes #555, though this may not be our permanent solution.
- Replace `np.bool` with `bool`, because it's being deprecated.
- Calculate IJK as needed within `KernelTransformer`, `Dataset.get_studies_by_mask`, and `MetaEstimator`.
- Fix bug in `Dataset.get_studies_by_label` in which, when the provided label was missing from the `Dataset.annotations` DataFrame, all Dataset IDs would be returned without so much as a warning.
- Replace basically every use of IJK with XYZ... hopefully I caught it all!
- Restructure the kernel tests to loop through parameters rather than having separate tests that are mostly duplicates of one another.
- Pin nilearn version to less than 0.8.0, to avoid the changes to the MNI152 template.

[FIX] Separate IJK calculation from coordinate space conversion

---

nimare/meta/cbma/base.py
nimare/meta/cbma/mkda.py

Closes None, but I'm trying to find a solution for Jennifer Barredo's memory issues, as reported in https://neurostars.org/t/nimare-allocating-resources-to-avoid-memory-crashes/20251
- Delete variables as they become unnecessary within CBMA (especially MKDAChi2) Estimators' FWE correction methods. I don't think this will make a huge difference, but it could help.

[REF] Reduce memory in CBMA Estimators

---

.circleci/config.yml
Makefile
nimare/tests/test_estimator_performance.py
nimare/tests/utils.py

Closes None.
- Move the smoke tests in `test_estimator_performance` into a new job only run on Python 3.6.
- Move utility functions in `test_estimator_performance` into `tests.utils`.
- Take coverage reports from unit tests, performance tests, and performance smoke tests, and merge them before uploading.

[TST] Reorganize tests for speed

---

Dockerfile
nimare/info.py

Closes None.
- Add pytest to docs dependencies.
- This is necessary to use `get_test_data_path`, but I will probably move the 21 pain dataset to resources in the future (in which case we'd use `nimare.utils.get_resources_path` instead). 
- Also remove seaborn from any dependencies.

[FIX] Add pytest to docs dependencies

---

nimare/annotate/__init__.py
nimare/decode/__init__.py
nimare/meta/__init__.py

Closes #388.
- Add major classes and functions to parent module namespaces.

[REF] Add major classes/functions to parent namespaces

---

docs/cbma.rst
docs/index.rst
docs/links.rst
docs/methods.rst
docs/outputs.rst
nimare/info.py
nimare/meta/cbma/ale.py

Closes #510.
- Add "methods.rst" page with a TOC linking to the different methods-specific pages.
- Add "cbma.rst" page documenting the different elements of CBMAs, including the null methods and correction methods.
- Pin older `mistune` version to circumvent issue with `m2r`/`mistune 2.0.0` compatibility.
- Pin older version of `matplotlib` because `nilearn` 0.7.1 doesn't work with matplotlib 3.5.0. Hopefully I'll be able to revert this part when I tackle #611 and stop pinning nilearn.

[DOC] Improve documentation of CBMA and add methods pages

---

.github/release.yml
README.md
examples/02_meta-analyses/09_peaks2maps.py
nimare/cli.py
nimare/extract/extract.py
nimare/meta/kernel.py
nimare/meta/utils.py
nimare/workflows/peaks2maps.py

Closes #615, though I won't mark this as ready to review this until we have a consensus in that issue.
- Add "deprecated" directive to docstrings of functions and classes related to the Peaks2Maps algorithm.
- Add a deprecation warning to Peaks2MapsKernel.

Flag peaks2maps for removal in 0.0.13/0.1.0

---

nimare/meta/cbma/ale.py
nimare/meta/utils.py
nimare/stats.py
nimare/transforms.py
nimare/utils.py
setup.cfg

Closes None, but is related to https://github.com/NBCLab/nimare-paper/issues/21.
- Loop over voxels when calculating p-values from SCALE null distributions, rather than keeping the full arrays in memory.

[REF] Reduce SCALE memory usage

---

examples/02_meta-analyses/04_macm.py
examples/02_meta-analyses/05_plot_cbma_subtraction_conjunction.py
nimare/meta/cbma/ale.py
nimare/tests/test_meta_ale.py
setup.cfg

Closes #247. These changes don't really vectorize anything. If anything, it relies on for loops _more_ than before, but at least now there is parallelization and memory-mapping.
~~It would be good to parallelize this step at some point, but I'm probably not going to try to tackle that in this PR.~~ Well that resolution lasted about five minutes...
- Add `n_cores` parameter to ALESubtraction and allow parallelization of the null distribution generation procedure.
- Remove the `memory_limit` parameter from ALESubtraction and just use a memmap no matter what.
- Fix docstring issues in SCALE that I failed to catch in #597.
- Make SCALE's `xyz` parameter required and check the actual parameter a bit before using it.

Incorporate joblib into ALESubtraction and fix SCALE docstring

---

nimare/base.py

Closes #651.
- Remove the `aggressive_mask` key at the beginning of `MetaEstimator._preprocess_inputs()` if it's defined. Basically, this redefines `aggressive_mask` from scratch any time `fit` is called.
- Mask data with the aggressive mask only if that aggressive mask is defined. 
- At first glance, this should be a bug that's come up already, and yet it hasn't. I assume there's a reason why CBMAEstimators loading `ma_maps` haven't failed due to a missing `aggressive_mask` key in `inputs_`, but I don't know what it is at the moment.

Do not inherit IBMAEstimator's aggressive_mask from previous Datasets

---

examples/02_meta-analyses/06_plot_compare_ibma_and_cbma.py
examples/02_meta-analyses/07_macm.py
examples/02_meta-analyses/09_plot_simulated_data.py
nimare/base.py
nimare/decode/continuous.py
nimare/decode/discrete.py
nimare/meta/cbma/ale.py
nimare/meta/cbma/base.py
nimare/meta/cbma/mkda.py
nimare/tests/test_meta_ale.py
nimare/tests/test_meta_ibma.py
nimare/workflows/scale.py

Closes #634.
- Return `results` from `Estimator.fit`, but do not store the object as an attribute of the `Estimator`.
- Ditto for `Decoder`s.
- Update tests and examples accordingly.

Stop storing MetaResults as attributes of fitted Estimators

---

docs/conf.py
docs/references.bib
examples/02_meta-analyses/08_plot_cbma_subtraction_conjunction.py
nimare/annotate/cogat.py
nimare/annotate/gclda.py
nimare/annotate/lda.py
nimare/decode/continuous.py
nimare/decode/discrete.py
nimare/decode/encode.py
nimare/meta/cbma/ale.py
nimare/meta/cbma/base.py
nimare/meta/cbma/mkda.py
nimare/meta/ibma.py
nimare/meta/kernel.py
nimare/transforms.py
setup.cfg

Closes #665.
Changes proposed:
- Replace references sections with footbibliographies.
- Add `sphinxcontrib-bibtex` to doc dependencies.

Use BibTeX citations in documentation

---

nimare/decode/continuous.py
nimare/meta/cbma/ale.py
nimare/meta/cbma/base.py
nimare/meta/cbma/mkda.py
nimare/meta/kernel.py
nimare/meta/utils.py
nimare/tests/test_meta_ale.py
nimare/tests/test_meta_kernel.py
nimare/tests/test_meta_mkda.py

Closes None.
- Dropping the memory-mapping option for Estimators and kernel transformers in this PR to rebase the PR #676  that supports the use of sparse arrays.

Dropping the memory-mapping option for Estimators and kernel transformers

---

nimare/io.py

Closes #666.
- small optimization that reduces `convert_neurosynth_to_dataset` runtime from ~7min to ~3min.
- I profiled these changes with:
```python
from nimare.extract import fetch_neurosynth
from nimare.io import convert_neurosynth_to_dataset
neurosynth_db = fetch_neurosynth(
data_dir='.',
version="7",
source="abstract",
vocab="terms",
)[0]
neurosynth_dset = convert_neurosynth_to_dataset(
coordinates_file=neurosynth_db["coordinates"],
metadata_file=neurosynth_db["metadata"],
annotations_files=neurosynth_db["features"],
feature_groups=['alzheimer']
)
```

Optimize locating coordinates in convert_neurosynth_to_dataset

---

nimare/decode/continuous.py
nimare/meta/cbma/base.py
nimare/meta/cbma/mkda.py
nimare/meta/kernel.py
nimare/meta/utils.py
nimare/tests/utils.py
setup.cfg

Closes None.
- Replace the 4D array in the (M)KDA with a list of 3D sparse arrays (one for each experiment) to avoid the high memory peak in the `KernelTransformer.transform` and `meta.utils.compute_kda_ma`.
There is probably a better way to introduce the sparse array here, but the current proposal works well with almost no modification to the kernel transformer.

Reduce memory usage of `KernelTransformer.transform` and `meta.utils.compute_kda_ma`

---

nimare/dataset.py
nimare/tests/test_dataset.py
nimare/transforms.py

Closes #465.
- Check for `z_stat` in `Dataset.coordinates.columns`.
- Check if there are values with `z_stat >= 0` AND `z_stat < 0` in `Dataset.__init__()` and when the `ImagesToCoordinates.transform()` is applied.

Add warning when coordinates dataset contains both positive and negative z_stats

---

docs/outputs.rst
nimare/meta/ibma.py
nimare/tests/test_meta_ibma.py
setup.cfg

Closes None, but is related to #277.
- Clean up some of the IBMA code.
- Add "se" to IBMA results, for applicable Estimators.
- Add "sigma2" to SampleSizeBasedEstimator outputs.
- Document the additional outputs in `docs/outputs.rst`.

Add parameter estimate standard error to IBMA results

---

.github/workflows/testing.yml
.github/workflows/update-changelog.yml
CHANGELOG.md

Closes None.
- Fix the admonitions that were reformatted by update-changelog Action. 
- Remove bullet points from multiline elements by having everything on a single line.
- Reorder the release versions by switching the latest version 0.0.12rc6 with 0.0.12rc3. 
- Add links to the full changelog to the headings to match the format of the update-changelog Action.

Fix CHANGELOG formatting issues

---

README.md
docs/index.rst
docs/references.bib
nimare/workflows/ale.py
nimare/workflows/conperm.py
nimare/workflows/macm.py
nimare/workflows/scale.py

Closes #710.
- Create sections on citing NiMARE to `README.md` and `docs/index.rst`.
- Add Zenodo and NeuroLibre references to workflow boilerplates.
- The Zenodo one is for 0.0.12rc7, but I added a note about grabbing the appropriate version's DOI.
- The conperm boilerplate is no longer accurate since we switched to using nilearn.
- I didn't add duecredit citations for the DOIs, but given #694, I don't know if it's worth it.
- Add the NeuroLibre badge as well.

Add citation information to documentation

---

nimare/meta/ibma.py

Closes #714.
- Use beta maps instead of z maps in PermutedOLS.

Use beta maps in PermutedOLS instead of z maps

---

docs/dev_guide.rst

Closes None, but is related to #701.
- Add section on project maintenance to developer's guide.

Add information about maintaining NiMARE to developer's guide

---

setup.cfg

using pandas 1.0.3, and 1.0.4 throw errors, but 1.1.0 does not when assigning values to columns that do not yet exist in a pandas dataframe: 
(this line)
https://github.com/neurostuff/NiMARE/blob/cb542af17c4f969afd05e4fd381a1200a1e4817c/nimare/meta/cbma/base.py#L127
Closes # None.
- make minimal pandas version 1.1.0
-

Pin minimum version of pandas

---

nimare/generate.py
nimare/meta/cbma/ale.py
nimare/meta/cbma/base.py
nimare/meta/cbma/mkda.py
nimare/meta/kernel.py
nimare/meta/utils.py
nimare/tests/test_meta_ale.py
nimare/tests/utils.py
nimare/utils.py

Closes #692.
- Create the MA maps for all studies in `compute_ale_ma` and return a 4D sparse array.
- Return sparse array by `ALEKernel._transform` and `KernelTransformer.transform`.
- Add support for `ma_maps` 4D sparse array in `ALE` and `CBMAEstimator`. This will involve adding support for sparse array in `ALE._compute_summarystat_est`, `ALE._determine_histogram_bins`, and `ALE._compute_null_approximate`.

Use sparse array in ALE, ALESubtraction, SCALE, KDA, and MKDADensity

---

examples/01_datasets/02_download_neurosynth.py
nimare/decode/base.py
nimare/decode/continuous.py
nimare/tests/utils.py

Closes None.
Currently, `CorrelationDecoder` takes a long time to be trained. Depending on the number of studies per feature, it takes around 13 min per feature (i.e., per iteration). For large databases like Neurosynth, which has 3228 features, it will take ~29 days. Adding the parallelization option reduces the computation time by a factor of `n_cores`. 
- Add `n_cores` parameter to use for parallelization.

Add parallelization option to `CorrelationDecoder` and `CorrelationDistributionDecoder`

---

nimare/annotate/lda.py

Closes None. This PR addresses the `TODO`:
https://github.com/neurostuff/NiMARE/blob/a4a7d1672f901ff5fca4cfdc91bfb829e0a00071/nimare/annotate/lda.py#L103-L104
- Append the top 3 weighted words from each topic name in the LDA annotation: `LDA50__1_word1_word2_word3`.

Append the top 3 words to LDA topic names

---

nimare/meta/utils.py

- Optimize `compute_kda_ma`
I was trying to speedup `MKDAChi2()` and made some changes to the matrix operations in `compute_kda_ma`, which could half the running time. Please feel free to make any revisions, as I could only test under my specific case.
- `nonzero_idx` is not sorted after the change, but I guess it's not an issue.
- I did not fully test against `sum_overlap=True`, in which `counts` could be a list.
I also found that parallelize this loop with joblib could speedup the process by another small percent. So, I was wondering if there is a way to pre-calculate `ma_maps` for all the files in a dataset and reuse them. I saw that many functions support using saved MA maps internally through `self.inputs_["ma_maps"]`, but I did not find a way …

Optimize compute_kda_ma

---

examples/02_meta-analyses/07_macm.py

Closes None.
- I think `atlas["maps"]` is already a `nibabel.nifti1.Nifti1Image` object. Using `nib.load` on `atlas["maps"]` will raise the error:
```
TypeError: stat: path should be string, bytes, os.PathLike or integer, not Nifti1Image
```

Fix MACM analysis example

---

setup.cfg

Since version 0.9.1, `nilearn` declares extra dependencies for its plotting capabilities.
~This PR drops the explicit dependency on a bounded version of `matplotlib` and let it be installed transitively through `nilearn`. Another benefit is to allow projects depending on `NiMARE` explicitly or transitively to install more recent versions of matplotlib which provides wheels for Python 3.10+.~
This PR drops the upper bound of the matplotlib requirement to allow install of more recent versions which provides wheels for Python 3.10+.

Remove upper bound for matplotlib version

---

examples/01_datasets/02_download_neurosynth.py

small syntax issue in https://nimare.readthedocs.io/en/latest/auto_examples/01_datasets/02_download_neurosynth.html#sphx-glr-auto-examples-01-datasets-02-download-neurosynth-py. `download_abstracts` is directly imported instead of what might have earlier been `from nimare.extract as extract`
also wanted to indicate `biopython` is required for `download_abstracts` so error doesn't get buried among the prints for neurosynth-data download

Fix neurosyth download_abstracts example; inc biopython

---

.github/workflows/linting.yml
.github/workflows/python-publish.yml
.github/workflows/testing.yml
nimare/__init__.py
setup.cfg

Closes None.
- Add deprecation warnings when running NiMARE on Python 3.6 or 3.7.
- Run Unit Tests of python 3.6 on ubuntu-20.04, since ubuntu-latest does not support python 3.6.

Raise deprecation warnings with Python 3.6 and 3.7

---

nimare/meta/cbma/base.py
nimare/meta/kernel.py
nimare/tests/test_decode_continuous.py
nimare/tests/test_meta_ale.py
nimare/tests/test_meta_kernel.py

Closes #630.
- Remove "dataset" `return_type` option from kernel transformers.
- I'm keeping `KernelTransformer._infer_names()`, just in case someone wants to generate image names and saves them in the `Dataset.images` dataframe for `CorrelationDistributionDecoder`, as shown in the test `test_CorrelationDistributionDecoder_smoke()`.

Remove "dataset" `return_type` option from kernel transformers

---

.github/ISSUE_TEMPLATE/config.yml
CONTRIBUTING.md
README.md
docs/conf.py
docs/index.rst

Closes None.
- Link to NeuroStars software support category instead of the general category (which defaults new posts to "Neuro Questions").
- Add badges to link to the GitHub repo, so it's easier to go from the RTD site to the code.
- Fix Nilearn intersphinx link.

Link to NeuroStars software support category instead of neuro questions

---

nimare/dataset.py
nimare/transforms.py

Closes None.
`pandas.DataFrame.append` is deprecated and will be removed in a future version of [pandas](https://pandas.pydata.org/docs/whatsnew/v1.4.0.html#whatsnew-140-deprecations-frame-series-append).
- Replace `pandas.DataFrame.append` with `pandas.concat`.

Replace `pandas.DataFrame.append` with `pandas.concat`

---

nimare/diagnostics.py

Closes None.
This parameter will allow users to remove small clusters from the diagnostics.
- Add `cluster_threshold` option to Diagnostics
- Small refactoring.

Add `cluster_threshold` option to Diagnostics

---

setup.cfg

Closes #787 
- remove codecov as dependency
-

[MAINT] remove codecov

---

nimare/decode/base.py
nimare/decode/continuous.py
nimare/tests/test_decode_continuous.py

Closes #781.
- New method: `load_imgs`. Load pre-generated meta-analytic maps for decoding.
- New attribute: `results_`. MetaResult object containing masker, meta-analytic maps, and tables. This attribute replaces `masker`, `features_`, and `images_`.

Support pre-generated maps in `CorrelationDecoder`

---

.github/workflows/update-changelog.yml
.readthedocs.yml
CHANGELOG.md

Remove RC versions from Changelog

---

setup.cfg

Closes None.
This is an attempt to unpin the maximum version of numpy, given that this issue `https://github.com/numba/numba/issues/8615` was closed. 
Hopefully, this will address one of the issues we have with installing nimare in a pyodide kernel: https://github.com/neurostuff/NiMARE/pull/785#issuecomment-1528079272.

Unpin numpy version

---

nimare/io.py
nimare/nimads.py
nimare/tests/test_io.py

Closes # .
- fix the conversion of studyset to dataset when sample size is not reported
-

handle case of no sample size being reported

---

docs/outputs.rst
examples/02_meta-analyses/08_plot_cbma_subtraction_conjunction.py
examples/02_meta-analyses/10_plot_cbma_workflow.py
nimare/correct.py
nimare/diagnostics.py
nimare/results.py
nimare/tests/test_diagnostics.py
nimare/tests/test_workflows.py
nimare/workflows/ale.py
nimare/workflows/cbma.py

Closes #800 .
- Add Corrector and Diagnostics attributes to MetaResult object.
- Diagnostics.transform now returns a MetaResult object.
- Maps and tables from diagnostics are now added to `maps` and `tables` dictionaries.

Add Corrector and Diagnostics attributes to MetaResult object

---

nimare/reports/base.py
nimare/reports/default.yml
nimare/reports/figures.py
nimare/reports/report.tpl

Closes #814.
- Use iframes for Connectomes instead, given that its aspect ratio is fixed. 
- Keep the size of the heatmap fixed by including the str in the HTML directly.
- Set the size of the heatmap proportional to the number of rows (number of studies) and columns (number of clusters).

Fix the aspect ratio and size of the heatmap in Reports

---

nimare/utils.py

references neurostuff/neurostore#587  .
- allows the manipulation of sample_size meta-data when it contains null values
-

[FIX] handle null values in metadata

---

.github/workflows/testing.yml
.readthedocs.yaml
Makefile
nimare/meta/cbmr.py
nimare/meta/models.py
nimare/tests/test_meta_cbmr.py
pyproject.toml
setup.cfg

Closes #806.
- Make `torch` optional.
- Test raise ImportError.

Make `torch` optional

---

nimare/transforms.py
setup.cfg

Closes #842.
- Add `new_file` to a copy of `images_df` instead.

Fix compatibility of ImageTransformer with Pandas 2.1.2

---

nimare/reports/base.py
nimare/reports/default.yml
nimare/reports/figures.py

Closes #847.
- Adding a similarity-sorted correlation matrix figure to the summary section of the IBMA reports.

Add similarity correlation matrix figure to IBMA reports

---

nimare/meta/cbma/base.py
nimare/meta/cbma/mkda.py
nimare/meta/kernel.py
nimare/meta/utils.py
nimare/reports/base.py
setup.cfg

`sum_across_studies` returns an array where study counts are sequentially added to a single dense matrix, rather than compiling an exhaustive matrix containg all study-level count data. 
This is much more effecient memory and compute wise, enabling MKDA Chi squared with Neurosynth as reference, using <1GB of memory.

Add `sum_across_studies` to kda

---

nimare/meta/cbma/base.py
nimare/meta/cbma/mkda.py
nimare/meta/kernel.py
nimare/meta/utils.py
nimare/reports/base.py
nimare/tests/test_meta_kernel.py
setup.cfg

- Implement "summary_array" return type for `MKDAKernel`, which convolves kernels to coordinates in a 3D dense volume, summing counts in place, saving substantial memory and compute. 
- Using numba to speed up sphere kernel convolution
- @jdkent set types to int to reduce memory usage
- Minor improvements throughout
For large-scale `MKDAChi2` (i.e. using Neurosynth dataset), memory footprint is reduced ~18-20x (25GB to 1.2GB), and computation is sped up ~3.2x.

Optimize compute_kda_ma for memory and speed

---

nimare/utils.py

Closes # .
- the neurovault collections are a bit messy and sometimes contrast names are the names of the images themselves (and not a reference to their relative path)
- this pull request makes sure the id columns are not checked to contain valid image extensions (since some of them currently do).

[FIX] do not check id columns for image extensions

---

.readthedocs.yaml
nimare/meta/ibma.py
nimare/reports/base.py
nimare/reports/default.yml
nimare/reports/figures.py
setup.cfg

Closes None.
- Add a bar plot showing the percentage of valid voxels per study.
- Add a summary stats plot showing different statistics from the distribution of the images.

Add advanced plots to IBMA report

---

nimare/annotate/gclda.py
nimare/correct.py
nimare/meta/cbma/ale.py
nimare/meta/cbma/base.py
nimare/meta/cbma/mkda.py
nimare/meta/ibma.py

The `FWECorrector` was written generally, such that methods beyond bonferoni and montecarlo could be specified if an `Estimator` implements one.
However, as of yet no such alternate method is implemented, and this generic organization obfuscates the API for the `FWECorrector`, as its not clear what possible options are implmeneted by estimators for monte carlo correction. 
Here, I make this API more explicit by:
* Makes montecarlo and bonferroni only possible options for `FWECorrector`, instead of any possible  yet to defined method
* Sets `n_iters` to 1000 across the board
* Makes other `montecarlo` arguments directly available to `FWECorrector`

Clarify FWECorrector arguments

---

examples/02_meta-analyses/04_plot_estimators.py
examples/02_meta-analyses/08_plot_cbma_subtraction_conjunction.py
nimare/annotate/gclda.py
nimare/base.py
nimare/cli.py
nimare/correct.py
nimare/decode/base.py
nimare/estimator.py
nimare/meta/cbma/ale.py
nimare/meta/cbma/base.py
nimare/meta/cbma/mkda.py
nimare/meta/ibma.py
nimare/meta/kernel.py
nimare/workflows/cbma.py
nimare/workflows/macm.py

Closes # .
- this clarifies docstrings for use in the config file, and makes sure defaults are set correctly
-

[FIX] fwe docstrings

---

setup.cfg

Closes # .
Since I'm using return_as, it was only introduced in joblib at version 1.3.0, so setting that as the minimum version
https://joblib.readthedocs.io/en/stable/developing.html#release-1-3-0-2023-06-28
- 
-

min joblib 1.3.0

---

.github/workflows/testing.yml
nimare/meta/ibma.py
setup.cfg

Update Nilearn API _check_same_fov

---

nimare/meta/ibma.py
setup.cfg

Closes None.
- Add the correction for multiple contrasts within a study in Stouffer's IBMA, implemented in https://github.com/neurostuff/PyMARE/pull/117

Add correction for multiple contrasts within a study in Stouffer's IBMA

---

nimare/reports/figures.py
setup.cfg

Closes #886  .
- colormaps API changed: https://github.com/matplotlib/matplotlib/issues/20853

[FIX] bump matplotlib version and update usage of get_cmap

---

nimare/meta/ibma.py
nimare/reports/base.py
nimare/tests/test_meta_ibma.py

Closes #888.
As documented in the issue, the correlation matrix for calculating the inflation reduction term in Stouffers, and the same matrix for showing the similarity between IBMA studies in the report, should be calculated in signal voxels.
- Here, we calculate that matrix in the Stouffers._preprocess_input method and use the same in the report if it exists.

Compute correlation matrix in signal voxels

---

setup.py

[FIX] fix name of nimare to be pep 625 compliant
