- examples/save_nidm_to_dset.ipynb
Closes # None
[the notebook](https://github.com/jdkent/NiMARE/blob/save_nidm_to_dset/examples/save_nidm_to_dset.ipynb)
- changes paths to database file
> [FIX] save_nidm_to_dset.ipynb

- nimare/dataset/dataset.py
- nimare/dataset/extract.py
Add a more convenient way to go from sleuth files to NiMARE Database object. Should be backward compatible.
> convert_sleuth_to_database

- MANIFEST.in
- nimare/meta/cbma/utils.py
- nimare/version.py
- setup.py
* moved `appdirs` import to `_get_checkpoint_dir` and added to the extra requirements
* installing `english_spelling.csv`
> changes in setup and requirements

- nimare/__init__.py
this will suppress all warnings. we should dig into which module may be resetting warnings.
> fix: suppress all warnings for now

- nimare/cli.py
- nimare/workflows/ale.py
- adding new command line options for threshold parameters
- more help text
- saving input coordinates to the output directory (this will help with implementing meta-analytic regression @mriedel56)
```
Usage: nimare ale [OPTIONS] SLEUTH_FILE
Method for performing coordinate based meta analysis that uses a
convolutionwith a 3D Gaussian to model activation. Statistical inference
is performed using a permutation based approach with Family Wise Error
multiple comparison correction.
Options:
--output_dir TEXT               Where to put the output maps.
--output_prefix TEXT            Common prefix for output maps.
--n_iters INTEGER               Number of iterations for permutation
testing.  [default: 10000]
--cluster_forming_threshold_p FLOAT
Voxel p-value threshold used to create
clusters. …
```
> ale CLI cleanup

- nimare/workflows/cluster.py
- nimare/workflows/scale.py
Closes none.
-changed option to follow precedent set in `ale` cli
-updated help, tested `scale` cli
> Update, test `scale` cli.

- .zenodo.json
> Add Dylan to zenodo

- nimare/dataset/extract.py
- nimare/meta/cbma/ale.py
- nimare/workflows/ale.py
- nimare/workflows/ibma_perm.py
Closes None.
- Add ALE subtraction analysis to ALE CLI
- Allow convert_sleuth tools to accept multiple text files and then merge them in one dataset
- Improve ALE/SCALE/subtraction analysis docstrings
- Update conperm CLI arguments
> [ENH] Add ALE subtraction analysis to CLI

- docs/api.rst
- nimare/__init__.py
- nimare/cli.py
- nimare/dataset/dataset.py
- nimare/io.py
- nimare/meta/cbma/ale.py
- nimare/workflows/ale.py
- nimare/workflows/conversion.py
- nimare/workflows/ibma_perm.py
- nimare/workflows/macm.py
Closes #36.
- Add ALE MACM workflow.
- Add Neurosynth-to-NiMARE and Sleuth-to-NiMARE workflows.
- Finish boilerplates for ALE meta-analysis, ALE MACM, and contrast permutation workflows.
- Fix minor bug in ALE permutation code.
- Fix minor bug in convert_sleuth_to_dataset.
- Enable logging throughout package.
> [ENH] Add MACM and Neurosynth/Sleuth conversion workflows

- README.md
- docs/index.rst
Closes #97.
- Add badges to README.
- Add badges to docs site.
> [DOC] Add badges

- nimare/dataset/dataset.py
- nimare/decode/discrete.py
- nimare/parcellate/cbp.py
- nimare/stats.py
Closes None.
- Use better pandas practices to dramatically speed up Dataset initialization (Neurosynth now only takes ~2.5-3 mins on my laptop)
- Make discrete decoding functions compatible with `stats.p_to_z` (does not accept signs argument) and `stats.one_way`/`stats.two_way` (both return chi-squared values, not p-values)
> [FIX, ENH] Fix discrete decoding and speed up Dataset initialization

- nimare/annotate/text.py
- nimare/dataset/dataset.py
- nimare/decode/continuous.py
Closes None. References #115.
- Add `slice` method to Datasets, which returns a new dataset based on requested IDs.
- Add download_abstracts function in annotate.text.
> [ENH] Add slice method for Datasets

- nimare/resources/nidm_pain_dset_with_subpeaks_docker.json
Closes #92.
- Remove absolute paths in test dataset.
> [FIX] Remove absolute paths in dataset

- nimare/annotate/text.py
- nimare/dataset/dataset.py
Closes #123.
- Add `_load_texts` and `get_texts` functions to Dataset class.
- Get `download_abstracts` function working.
> [ENH] Add texts field to Dataset

- nimare/annotate/text.py
- nimare/annotate/topic/gclda.py
Closes None.
- GCLDA is still very slow and bloated, so we'll want to streamline it in the future, but it's working now.
> [FIX] Fix up GCLDA and text extraction methods

- README.md
- docs/index.rst
Closes None.
- Replace Slack badge with Mattermost one in README and in docs.
> [DOC] Change outdated Slack link to Mattermost

- nimare/__init__.py
- nimare/annotate/topic/gclda.py
- nimare/base/annotate.py
- nimare/base/base.py
- nimare/base/decode.py
- nimare/base/estimators.py
- nimare/base/meta.py
- nimare/base/misc.py
- nimare/dataset/dataset.py
- nimare/decode/continuous.py
- nimare/decode/discrete.py
- nimare/decode/encode.py
References #130, but does not close. The model could still do with a good review and is still pretty slow. I would like to see if we can optimize it before closing the issue.
- Move several attributes into new `data` and `topics` dictionary attributes. Only done to attributes that the user won't generally care about.
- I would like to eliminate `data` in the future, if possible, by relying solely on the input DataFrames `counts_df` and `coordinates_df`.
- Remove several methods that were extraneous.
- Move `load` and `save` methods out of Dataset class definition.
- Reorganize base classes so that GCLDAModel and Dataset can inherit.
- The problem is that Dataset now inherits from NiMAREBase, but NiMAREBase was defined in the same file as Estimator …
> [REF] Refactor GCLDA model

- nimare/workflows/ale.py
Closes #134.
- Add new argument (`--fwhm`) to allow manual specification of FWHM (across all studies/experiments in dataset) for ALE meta-analysis.
- Update boilerplate to accurately describe whichever method was used.
> [ENH] Add FWHM argument to ALE CLI workflow.

- nimare/dataset/dataset.py
- nimare/io.py
Closes #132.
- Add “Talairach” to nimare.io.convert_sleuth_to_dict.
- Combine multiple Sleuth files based on contrasts rather than full studies. This will still hide duplicate contrasts, but at least studies with multiple contrasts spread across files will be fine.
- Change how transforms are handled in Dataset initialization and explicitly support “MNI”, “TAL”, and “Talairach”.
> [ENH] Support additional space descriptors

- .zenodo.json
Closes None.
- Add @Julio-A-Yanes to Zenodo file, based on his contributions during Coastal Coding.
> [MAINT] Add Julio to Zenodo file

- nimare/annotate/ontology/__init__.py
- nimare/annotate/ontology/cogat.py
- nimare/annotate/ontology/cogpo.py
- nimare/annotate/topic/boltzmann.py
- nimare/annotate/topic/gclda.py
- nimare/annotate/topic/lda.py
- nimare/annotate/vector/text2brain.py
- nimare/annotate/vector/word2brain.py
- nimare/decode/continuous.py
- nimare/decode/discrete.py
- nimare/decode/encode.py
- nimare/meta/cbma/ale.py
- nimare/meta/cbma/mkda.py
- nimare/parcellate/cbp.py
- nimare/parcellate/mamp.py
- nimare/parcellate/mapbot.py
Closes None.
- Add references to many docstrings.
- Add parameters to MKDA/KDA CBMA docstrings.
> [DOC] Update docstrings

- .circleci/config.yml
- nimare/io.py
- nimare/tests/test_cbma_ale.py
- nimare/tests/test_cbma_mkda.py
- nimare/tests/test_cbma_scale.py
- nimare/tests/test_ibma.py
- nimare/tests/test_ibma_fsl.py
- requirements.txt
Closes None.
- Split FSL-based and Python-based IBMA tests, so we can ignore the FSL-based ones.
- Update CircleCI config file.
> [FIX, TST] Fix CircleCI

- MANIFEST.in
Closes None.
- Add tests/data folder to manifest so files can be found.
> [DOC] Update Manifest to work with examples.

- .circleci/config.yml
Closes None.
- This should streamline testing a bit more.
> [TST] Improve CircleCI configuration

- nimare/base/estimators.py
- nimare/decode/continuous.py
- nimare/decode/discrete.py
- nimare/decode/encode.py
- nimare/meta/cbma/__init__.py
- nimare/meta/cbma/ale.py
- nimare/meta/cbma/kernel.py
- nimare/meta/cbma/mkda.py
- nimare/meta/esma.py
- nimare/meta/ibma.py
- nimare/utils.py
- nimare/workflows/peaks2maps.py
Closes None.
- Add `Estimator.fit` docstring, which will be useful for the API documentation.
- Update some of the outdated docstrings.
- Add docstring for ALESubtraction.
- Fix Peaks2MapsKernel and corresponding workflow.
> [FIX, DOC] Improve docstrings and update Peaks2Maps

- nimare/annotate/ontology/cogat.py
- nimare/annotate/ontology/cogpo.py
- nimare/annotate/topic/boltzmann.py
- nimare/annotate/topic/gclda.py
- nimare/annotate/topic/lda.py
- nimare/annotate/vector/text2brain.py
- nimare/annotate/vector/word2brain.py
- nimare/decode/continuous.py
- nimare/decode/discrete.py
- nimare/decode/encode.py
- nimare/meta/cbma/ale.py
- nimare/meta/cbma/mkda.py
- nimare/meta/cbma/model.py
- nimare/meta/cbma/peaks2maps.py
- nimare/meta/cbma/utils.py
- nimare/meta/esma.py
- nimare/parcellate/cbp.py
- nimare/parcellate/mamp.py
- nimare/parcellate/mapbot.py
- nimare/references.py
- nimare/stats.py
- nimare/utils.py
- nimare/workflows/cluster.py
- nimare/workflows/ica.py
Closes #160.
- Move BibTeX- and DOI-based duecredit citations into new `references` submodule.
- Clean up model-based CBMA classes.
> [DOC, REF] Add references submodule

- nimare/info.py
Closes None. Fixes a bug introduced by #165.
- Add `m2r` (markdown-to-restructuredtext conversion) to list of doc-specific requirements in `info.py`.
> [FIX, DOC] Add m2r to doc requirements

- docs/requirements-dev.txt
- nimare/info.py
Closes None. Actually fixes bug introduced in #165 and definitely not fixed by #167.
- Update docs/requirements-dev.txt because RTD isn't using the "doc" section of the requirements specified by setuptools in `nimare/info.py`.
> [FIX, DOC] Add m2r to docs-specific requirements file

- nimare/dataset.py
- nimare/meta/ibma.py
- nimare/utils.py
Closes None. Just a few small style issues to fix.
> [FIX, STY] Fix flake8 issues

- docs/conf.py
Closes None.
- Remove the click Sphinx extension from conf.py.
> [FIX] Remove click from conf.py

- .github/release-drafter.yml
- .zenodo.json
Closes None.
- Add release drafter config file.
- Also reorder authors in Zenodo file.
> [MAINT] Add release drafter

- README.md
- docs/index.rst
Closes None.
- Add PyPi and Zenodo badges to docs.
- Add RRID badge to docs and README.
> [MAINT] Add badges to README and RTD

- docs/api.rst
- docs/installation.rst
- nimare/annotate/topic/gclda.py
- nimare/base.py
- nimare/correct/correct.py
- nimare/meta/cbma/ale.py
- nimare/meta/cbma/kernel.py
- nimare/meta/cbma/mkda.py
Closes None. This is primarily meant to trigger the RTD build in CI, but it also does fix some broken links.
- Update API sections.
- Update some parameter object types.
> [DOC] Update API documentation

- Dockerfile
- create_dockerfile.sh
- examples/03_annotation/run_gclda.py
- examples/03_annotation/run_lda.py
- nimare/annotate/topic/gclda.py
- nimare/annotate/topic/lda.py
- nimare/extract/extract.py
Closes None.
- Change the location of MALLET in the Dockerfile
- Fix imports in LDA and GCLDA examples
- Fix pandas problems in LDAModel
> [FIX] Fix bugs in LDAModel and paths to MALLET

- .circleci/config.yml
Closes None.
- Shamelessly copies Tal’s work in PyMARE.
> [MAINT] Add workflow to autodeploy to PyPi

- .circleci/config.yml
Hopefully this will trigger deployment properly.
-
-
> [FIX] Mimic PyMARE's config more completely

- nimare/io.py
- `convert_sleuth_to_dataset` now allows for multi-line experiment names (which occur quite frequently in Sleuth output textfiles)
> [ENH] Make convert_sleuth_to_dataset more flexible

- nimare/correct/correct.py
- nimare/meta/cbma/ale.py
- nimare/meta/cbma/mkda.py
- nimare/tests/test_cbma_ale.py
- nimare/tests/test_cbma_mkda.py
Closes #215.
- Rename permutation to montecarlo re: multiple comparisons correction strategy.
> [REF] Rename "permutation" to "montecarlo"

- docs/api.rst
- nimare/meta/cbma/kernel.py
- nimare/workflows/ale.py
- nimare/workflows/cluster.py
- nimare/workflows/macm.py
- nimare/workflows/peaks2maps.py
- nimare/workflows/scale.py
Closes None.
- Update workflows given changes to API.
> [FIX] Update workflows given recent changes

- .readthedocs.yml
- docs/requirements-dev.txt
Closes None.
- Add RTD config file.
- Remove requirements-dev.
> [MAINT] Consolidate requirements files

- .zenodo.json
Closes None. Just prep for 0.0.3.
- Add info to Zenodo file.
> [MAINT] Add @nicholst's info to Zenodo file

- .codecov.yml
Closes None. I noticed the "ignore" folders weren't being ignored. The problem was that the config file was not valid.
- Change threshold from null to 0 to make file valid.
> [TST] Fix CodeCov config file

- nimare/meta/cbma/ale.py
Closes #243.
- Change one-sided p-values to two-sided.
- Drop group 2 > group 1 analysis, but use all voxels significant in either group 1 or group 2 meta-analyses.
> [REF] Eliminate duplication in ALESubtraction

- nimare/meta/cbma/ale.py
- nimare/tests/test_cbma_ale.py
- nimare/workflows/ale.py
Closes #242.
- Simplify interface for ALESubtraction. Images and threshold are no longer required.
- Drop voxel selection. ALESubtraction is now run on _all_ voxels.
- Remove warning about voxel selection from ALESubtraction docstring.
> [ENH] Remove voxel selection in ALESubtraction

- nimare/dataset.py
Closes None. This is a performance change that will be overridden by changes for #218. Dropping `.data` cuts the size of the Neurosynth dataset down from ~3.6GB to ~1.6GB.
- Drop `.data` attribute from Dataset objects. `.data` is the full dataset, in dictionary form.
> [REF] Drop Dataset.data attribute

- examples/04_decoding/plot_discrete_decoders.py
- nimare/annotate/gclda.py
- nimare/base.py
- nimare/decode/continuous.py
- nimare/decode/discrete.py
- nimare/meta/cbma/mkda.py
- nimare/tests/test_decode_continuous.py
- nimare/tests/test_decode_discrete.py
Closes #251, although it doesn't convert GCLDA-related decoders yet.
- Add base class for Decoders.
- Raise warning for failure to load sample sizes in CBMAEstimator, instead of raising an error.
> [ENH] Convert decoders to classes

- nimare/dataset.py
Closes None.
- Use nearest neighbor interpolation for resampling masks in `Dataset.get_studies_by_mask`.
> [ENH] Use nearest-neighbor interpolation for masks

- examples/02_meta-analyses/plot_generate_ma_maps.py
- examples/02_meta-analyses/plot_ibma.py
Closes None.
- Shows some of the new Estimators in the example.
> [DOC] Expand IBMA example

- docs/conf.py
- examples/02_meta-analyses/plot_ibma.py
- nimare/meta/ibma.py
- nimare/tests/test_ibma.py
Closes None, but references #196.
- Split Something into DerSimonianLaird and Hedges IBMA estimators
- Add IBMA estimator docstrings.
- Add PyMARE to intersphinx mapping.
> [ENH] Split DerSimonianLaird and Hedges IBMA estimators

- nimare/base.py
- nimare/tests/test_decode_discrete.py
Closes #259.
- Raise an error in Decoders if no features remain.
- Add an associated test.
> [FIX] Raise an error in Decoders if no features remain

- examples/02_meta-analyses/peaks2maps.py
- nimare/meta/kernel.py
Closes None, but thanks to @julio-a-yanes for noticing the problem(s).
Pending bugs:
1. `resample_to_mask=False` will still fail. We need to update the masker's mask with the resampled version before it will work.
2. Need to update the minimum tensorflow version and get things working with v2+.
- Update peaks2maps example.
- Fix masker handling in Peaks2MapsKernel.
> [FIX] Update peaks2maps w.r.t. recent changes in the API

- nimare/info.py
- nimare/meta/kernel.py
- nimare/meta/peaks2maps.py
- nimare/meta/utils.py
Closes #288 and closes #289.
- This required updating peaks2maps a fair amount. Luckily everything was still accessible via `tf.compat.v1` submodule.
- Fix masker handling in Peaks2Maps. Should be good now.
> [MAINT] Increase minimum tensorflow to 2.0.0

- .circleci/config.yml
- nimare/annotate/text.py
- nimare/base.py
- nimare/info.py
- nimare/transforms.py
Closes #292.
- Add steps in the CircleCI config for testing with Python 3.5 and 3.7.
- Drop 3.5 support and add 3.8 support.
- Make `nltk` an optional dependency.
- Drop `pyneurovault` as a dependency.
> [TST] Add tests for Python 3.7 and 3.8. Drop 3.5 support.

- README.md
Closes None. This is primarily to check GitHub Checks.
- Drop extra whitespace.
> [DOC] Remove whitespace from README

- nimare/io.py
- nimare/tests/data/test_sleuth_file.txt
- nimare/tests/test_io.py
Should deal with #309.
- Instead of checking 1-2 lines for contrast names in Sleuth text files, group contrasts based on contiguous lines starting with '//'.
- Add contrast with three name lines to test Sleuth file.
- Add check for sample size line for each contrast in Sleuth text files.
- Improve precision of Sleuth conversion test.
> [FIX] Support multiple header lines in Sleuth text files

- nimare/meta/ale.py
- nimare/meta/mkda.py
Closes None.
- In meta-analysis classes, use `NiMAREBase._check_ncores()` instead of reimplementing the same functionality.
> [REF] Reduce duplication by calling _check_ncores

- nimare/correct.py
- nimare/info.py
- nimare/tests/test_io.py
- nimare/tests/test_meta_ale.py
- nimare/tests/test_meta_mkda.py
Closes None.
- Add tests for `nimare.io.convert_sleuth_to_json()` and `nimare.io.convert_neurosynth_to_json()`.
- Test out more values for `n_cores` with `NiMAREBase._check_ncores()`.
- Remove `nltk` dependency. This is linked to #312.
> [TST] Improve nimare.io test coverage

- nimare/tests/test_decode_discrete.py
- nimare/tests/test_meta_ale.py
- nimare/tests/test_meta_ibma.py
- nimare/tests/test_meta_kernel.py
- nimare/tests/test_meta_mkda.py
- nimare/tests/test_meta_scale.py
Closes None.
- Cover saving and loading meta-analysis objects.
- Cover get_map in MetaResult.
> [TST] Improve meta-analysis tests

- nimare/base.py
- nimare/decode/continuous.py
- nimare/tests/test_decode_continuous.py
Closes #325.
- Add a smoke test for CorrelationDistributionDecoder.
- Fix a small bug in the decoder.
> [FIX, TST] Fix and test CorrelationDistributionDecoder

- nimare/info.py
- pyproject.toml
> [FIX] Update setuptools version

- pyproject.toml
> [FIX] Pin setuptools again

- nimare/dataset.py
Closes #335. 
- Add a private setter method for Dataset.ids, with a type and shape check.
- Use the new method for assignment of Dataset.ids.
> [FIX] Add private setter method for Dataset.ids

- nimare/extract/__init__.py
- nimare/extract/extract.py
- nimare/tests/test_extract.py
Closes #340.
- Copy `neurosynth.base.dataset.download()` to `nimare.extract.fetch_neurosynth()`.
- Copy `neurosynth.tests.test_base.test_dataset_download()` to `nimare.tests.test_extract.test_fetch_neurosynth()`.
> [ENH] Add Neurosynth data fetcher

- .circleci/config.yml
- nimare/base.py
- nimare/info.py
Closes None. In reviewing the dependencies to cite in the NiMARE manuscript, I noticed a few packages that might not be necessary.
- Remove `six` as a dependency. `six` is used for Python 2/3 compatibility, but we only support Python 3.5+.
- Remove `traits` as a dependency. `traits` isn't directly used anywhere in the package, although it could be a downstream dependency.
> [REF] Reduce dependencies

- nimare/correct.py
Closes #351.
- Remove an unused argument (alpha) in statsmodels function call within `FWECorrector`.
> [REF] Remove unused alpha argument in statsmodels call

- .zenodo.json
Closes # .
- Editing the .zenodo.json file to add Enrico Glerean's affiliation and orcid.
> [MAINT] Add Enrico Glerean's affiliation and ORCID

- .zenodo.json
@tsalo - not sure if you want to keep any specific order, so just added my name before Angie
> [MAINT] Add Dorota Jarecka to Zenodo file

- .zenodo.json
- docs/roadmap.rst
Closes None.
- Update roadmap.rst
- Add @jbpoline to the Zenodo file.
> [DOC] Update roadmap.rst

- nimare/meta/mkda.py
- nimare/tests/test_meta_mkda.py
Closes #361
ref #350, #343
- change vfwe array to float
I'll link to the relevant failed test in #343 when it's available.
> [FIX] Treat vfwe as an array of floats for KDA

- nimare/generate.py
- nimare/tests/test_generate.py
Closes #381 
- take max of 1 or whatever n_noise_foci is.
- add test to ensure length of dataset is correct.
> [FIX] respect n_noise_foci value

- nimare/meta/ale.py
Just adds #374 to #386 to make testing smoother.
> Add performance tweaks to ALE analytical null generation

- nimare/generate.py
Closes None
- changes default seed in `create_coordinate_dataset` to None, so that each time it is called it will generate a different random dataset.
> [FIX] Change default seed to None

- nimare/annotate/lda.py
Closes #366 .
- Add code, in the initialization of LDAModel, to automatically remove rows with empty text_column (abstract).
> [FIX] Remove rows with empty abstract before running LDAModel

- .circleci/config.yml
- setup.py
Closes #426.
- Switch from using `package_data` to `data_files` in setup.
- Include setup.py in CircleCI caching so that changes to _either_ setup.py or info.py will trigger environment build.
> [FIX] Include resources in library data files

- MANIFEST.in
- setup.cfg
- setup.py
Closes #426. #427 didn't fix the issue.
- List all paths (with no recursion) to resources that need to be packaged with the library in `setup.cfg`. Using `setup.cfg` over `setup.py` is based on https://gist.github.com/effigies/9bbb424535d6a1d838d6325191c0a736.
> [FIX] Fix packaging of resources

- nimare/info.py
Closes #399.
- Add `indexed_gzip >= 1.4.0` as a dependency.
> [MAINT] Add indexed_gzip as a dependency

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
Closes #None.
- Add an issue template config file to link to NeuroStars.
- Add specialized issue templates for bug reports and feature requests.
> [DOC] Add specialized issue templates

- .github/ISSUE_TEMPLATE/config.yml
Closes None.
- Fix the usage question link in the issue template choice page.
> [DOC] Fix NeuroStars link

- .circleci/config.yml
- .github/workflows/python-publish.yml
Closes #440.
- Add Action config for deployment.
- Remove deployment step from CircleCI.
> [MAINT] Switch to GitHub Actions for PyPi deployment

- docs/api.rst
- docs/index.rst
- docs/methods/decoding.rst
References #436 and is related to [this NeuroStars post](https://neurostars.org/t/nimare-decoding-results/18148). Still need to describe continuous decoders and encoders.
- Add new documentation page to describe Decoders.
- Include step-by-step descriptions of the methods used for `BrainMapDecoder` and `NeurosynthDecoder`.
> [DOC] Add decoding description page

- nimare/tests/test_transforms.py
- nimare/transforms.py
Closes #444  .
- `squeeze()` output to remove extra dimension 
- add check to ensure correct dimensionality of output
> [FIX] transform_images extra dimension

- nimare/meta/ibma.py
- nimare/tests/test_meta_ibma.py
Closes #449
- add squeeze() to the pymare outputs
- refactor ibma testing file to reduce me copy/pasting a lot.
> [FIX] Ensure IBMA results have the expected number of dimensions

- examples/01_datasets/plot_neurovault_io.py
- nimare/generate.py
- nimare/io.py
- nimare/tests/test_generate.py
- nimare/tests/test_io.py
references #341
- creates a downloader for neurovault and converts to a NiMARE data, but I did not see the nilearn function referenced in #341, will refactor.
> [ENH] add function to convert neurovault collections to a NiMARE dataset

- nimare/tests/test_utils.py
Closes #None .
- add test for memmap
-
> [TST] Add memmap test.

- nimare/correct.py
Closes None.
- Replace a single instance of "log_p" with "logp". I guess I missed this in #224.
> [FIX] Replace misspelled "log_p" with "logp"

- docs/api.rst
This addresses an issue identified in [this NeuroStars post](https://neurostars.org/t/using-neurovault-statistical-maps-in-nimare/19054/1).
- Add new `nimare.generate` class and functions to API.
- Add new `nimare.io` function to API.
> [DOC] Add new functions and classes to API documentation

- docs/dev_guide.rst
- nimare/generate.py
- nimare/info.py
- nimare/utils.py
- pyproject.toml
Closes #483.
- Add `flake8-isort` to test dependencies.
- Add `isort` configuration info to `pyproject.toml`. I took the settings from their website for maintaining compatibility with `black`.
- Run `isort` (after applying configuration) on NiMARE.
> [TST] Add flake8-isort to test dependencies

- docs/conf.py
- nimare/info.py
Closes #221.
- Add sphinx-copybutton to docs-specific requirements.
- Add sphinx-copybutton to docs configuration file.
> [DOC] Add sphinx-copybutton to docs requirements

- examples/03_annotation/plot_gclda.py
- nimare/annotate/gclda.py
Closes #491.
- Allow multiple symmetric pairs of subregions in GCLDA.
> [ENH] Support symmetric GCLDA topics with more than two subregions

- nimare/io.py
- nimare/tests/test_io.py
Closes #492.
- Check that collection was found and raise informative error.
- Add test for missing collection (778).
> [FIX] Add informative error when NeuroVault collection is not found

- examples/02_meta-analyses/plot_cbma.py
- examples/02_meta-analyses/plot_cbma_combine_estimators_and_kernels.py
- nimare/meta/cbma/ale.py
- nimare/meta/cbma/base.py
- nimare/meta/cbma/mkda.py
- nimare/tests/test_decode_continuous.py
- nimare/tests/test_estimator_performance.py
- nimare/tests/test_meta_ale.py
- nimare/tests/test_meta_kernel.py
- nimare/tests/test_meta_mkda.py
Closes #421.
- analytic --> approximate
- empirical --> montecarlo
- reduced_empirical --> reduced_montecarlo
> [REF] Rename CBMA null distribution generation methods

- nimare/transforms.py
Closes #508.
- Add overwrite option to `nimare.transforms.transform_images`. Default is False.
> [ENH] Add overwrite option to transform_images

- docs/api.rst
- examples/01_datasets/plot_dataset_io.py
- examples/01_datasets/plot_neurovault_io.py
- examples/01_datasets/transform_images_to_coordinates.py
- examples/02_meta-analyses/plot_compare_ibma_and_cbma.py
- examples/02_meta-analyses/plot_ibma.py
- nimare/base.py
- nimare/generate.py
- nimare/tests/test_transforms.py
- nimare/transforms.py
Closes #512.
- Add an ImageTransformer class that wraps around the transform_images function.
- Add the new class to the API docs.
- Test the new class.
- Replace uses of transform_images with ImageTransformer in examples and transformation code.
> [ENH] Add ImageTransformer class

- nimare/dataset.py
- nimare/tests/test_dataset.py
- nimare/utils.py
Closes #516.
- Add `Dataset.merge` method.
- Simplify `Dataset.slice` implementation.
- Split `nimare.utils.dict_to_coordinates` into two functions, creating new `nimare.utils.transform_coordinates_to_ijk` that can be called within `Dataset.merge`.
> [ENH] Add merge method to Dataset class

- nimare/base.py
- nimare/dataset.py
- nimare/meta/cbma/base.py
Closes #204.
- Add `drop_invalid` argument (default is True).
- Refactor `Dataset.get_[X]` methods to use shared code via new `Dataset._generic_column_getter` method.
> [ENH] Add `drop_invalid` option to `Dataset.get()` and `Estimator.fit()`

- nimare/correct.py
- nimare/tests/test_meta_mkda.py
Closes #524.
- Add class method `Corrector.inspect` to inspect MetaResults and identify all valid `method` values.
- Add test.
- Use f-strings in `nimare.correct`.
> [ENH] Add Corrector.inspect class method

- nimare/tests/conftest.py
- nimare/transforms.py
- nimare/utils.py
Closes None.
- Address cases of SettingWithCopyWarnings stemming from NiMARE's code.
> [TST, REF] Address pandas `SettingWithCopyWarning`s

- .circleci/config.yml
- nimare/base.py
- nimare/meta/cbma/base.py
- nimare/tests/conftest.py
- nimare/utils.py
Closes None, but fixes recent bug.
- Run `apt-get update` before `apt-get install make` to fix recent bug.
> [FIX] Update CircleCI config to fix recent bug

- nimare/base.py
- nimare/dataset.py
Closes #525.
- Add custom `__repr__` method for NiMAREBase and Dataset classes.
```python
import nimare
ale = nimare.meta.ALE(null_method="montecarlo", kernel__fwhm=8.)
print(ale)
```
> ALE(kernel_transformer=ALEKernel(fwhm=8.0), null_method='montecarlo')
```python
path = "/Users/taylor/Documents/tsalo/NiMARE/nimare/tests/data/neurosynth_laird_studies.json"
dset = nimare.dataset.Dataset(path)
print(dset)
```
> Dataset(17 experiments, space='mni152_2mm')
> [ENH] Add custom `__repr__` methods

- examples/02_meta-analyses/plot_cbma_subtraction_conjunction.py
Follow-up on  #515.
- Updated the citation for Enge et al. (2021) to the version now published in NeuroImage
> [DOC] Update citation for Enge et al. (2021)

- docs/about.rst
Closes None.
- Link to the new site for a top-level overview of the Neurostuff ecosystem.
-
> [DOC] Add admonition to about.rst linking to new site

- nimare/resources/database_file_manifest.json
Closes None, but relates to #554. Since the TFIDF features don't have a vocab at the moment, I'll remove it. However, this will be added back once there's an associated vocab file.
> [FIX] Drop NQ tfidf features from manifest

- nimare/meta/cbma/ale.py
- nimare/meta/cbma/base.py
- nimare/meta/cbma/mkda.py
- nimare/meta/ibma.py
- nimare/meta/kernel.py
Closes None. I am working on the NiMARE manuscript and realized that some docstrings were incomplete.
> [DOC] Fill out CBMA docstrings

- nimare/extract/extract.py
- nimare/resources/database_file_manifest.json
Closes None.
- Update the URL for the NeuroQuery database.
- Add the TFIDF 6308-term features back to our database manifest.
> [ENH] Add NeuroQuery 6308 vocab to resources

- .github/.release.yml
- .github/release-drafter.yml
Closes #448.
- Remove release-drafter config.
- Add GitHub release config.
> [INFRA] Replace release-drafter with GitHub release template

- CONTRIBUTING.md
Closes None, but stems from #448. Now that we use the release configuration file to automatically group PRs according to their purposes based on labels, we don't need PR title prefixes.
> Add a note about pull request titles to contributing docs

- docs/conf.py
- pyproject.toml
- setup.cfg
Closes None, but fixes a bug I introduced in #626.
- Change `long_description_content_type` from MD to RST.
- Remove a nonexistent file from pyproject.toml black settings.
> Fix field in setup.cfg

- .github/workflows/testing.yml
- Makefile
> Fix CI coverage upload

- .github/workflows/testing.yml
Closes None, but addresses issues not addressed in #647.
> Fix CodeCov some more

- docs/about.rst
- docs/links.rst
- setup.cfg
Closes #503.
- Add a section to the About NiMARE page about tools outside our ecosystem.
> Document other meta-analysis tools outside our ecosystem

- CODE_OF_CONDUCT.md
Closes None.
- Change the code of conduct enforcer from Tal to James.
> Change code of conduct enforcer to James Kent

- .github/workflows/update-changelog.yml
Closes #603.
- Add `prereleased` to activity types to trigger the update-changelog workflow.
> Automatically update `CHANGELOG.md` for prereleases as well

- .github/workflows/update-changelog.yml
Closes None.
- Fix tag name issue in update-changelog workflow
- Use `published` event type as recommended here https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release
> Fix tag-name issue in update-changelog workflow

- .github/workflows/update-changelog.yml
Closes None.
- Add PAT from my account to automatically commit release notes to CHANGELOG.
**Note:** In the future, it would be great to create an organizational bot account for these tasks.
> Add PAT to automatically commit release notes to `CHANGELOG.md`

- .github/workflows/update-changelog.yml
Closes None, but fixes a small typo from #701.
-
-
> Add quotes around commit message in YAML file

- .zenodo.json
Closes #711.
- Add Simon Eickhoff to the NiMARE Zenodo file.
> Add Eickhoff to Zenodo file

- docs/glossary.rst
- docs/index.rst
- nimare/meta/ibma.py
Closes #704.
- Add a glossary page (`docs/glossary.rst`).
- Add a couple of terms to the glossary page.
> Add a glossary page to the documentation

- nimare/meta/cbma/ale.py
- nimare/meta/cbma/base.py
- nimare/meta/cbma/mkda.py
- nimare/meta/kernel.py
Closes #661
- try not to copy numpy arrays when not necessary
> Remove extraneous `copy()` statements

- examples/01_datasets/02_download_neurosynth.py
Closes # .
- Line 77 error: "NameError: name 'download_abstracts' is not defined".
- Adding "extract" before "download_abstracts" solves the issue.
> Fix import in download_neurosynth example

- .zenodo.json
- nimare/dataset.py
- Optimized some dataframe operations in `dataset.get`, this should speed up reading large datasets (like the full Neurosynth).
Please feel free to make any revisions. Thanks!
> Optimize dataset.get

- nimare/annotate/lda.py
Closes None.
- Add the parallelization option and use it in the `LatentDirichletAllocation` model.
- Switch `learning_method` from `online` to the default `batch`.
> Enhance LDA annotator

- setup.cfg
Closes #756 
Closes #755 
Closes #758
- bump install version of matplotlib to 3.3.0
- restrict numpy versions
- make nibabel less than version 5.0.0 for now (but may want to actually fix underlying issue in future)
> [MAINT] Fix various errors due to major version changes in dependencies

- examples/03_annotation/04_plot_gclda.py
- examples/04_decoding/01_plot_discrete_decoders.py
- nimare/meta/kernel.py
- nimare/meta/utils.py
- nimare/tests/test_annotate_gclda.py
- nimare/tests/test_dataset.py
- nimare/tests/utils.py
- setup.cfg
Closes #759.
- Add header to `Nifti1Image` when passing an int64 array.
> Support nibabel 5.0.0

- docs/api.rst
- docs/cbma.rst
references #183 and #591
- add a note about the lack of implementation of SDM in the documentation
Relevant documentation: https://nimare--764.org.readthedocs.build/en/764/api.html
> [DOC] add note about SDM

- docs/api.rst
- nimare/io.py
- nimare/nimads.py
Closes # .
- add more documentation stubs for the nimads module
-
> [DOC] add proper documentation to nimads module

- .github/workflows/testing.yml
- docs/installation.rst
- docs/links.rst
- nimare/__init__.py
- nimare/annotate/cogat.py
Closes #779.
- Drop Python 3.6 and 3.7.
- Support Python 3.11.
> Drop support for Python 3.6 and 3.7

- README.md
changed the default landing to NiMARE from latest to stable, so updating badge to match
Closes # .
-
-
> [DOC] change readthedocs badge from latest to stable

- docs/index.rst
- examples/README.txt
> [DOC] Add neurolibre link

- .readthedocs.yml
- setup.cfg
> [MAINT] fix readthedocs

- nimare/correct.py
Closes None.
It would be nice to have some of the NiMAREBase features available in Corrector. For example, with `get_params()` we could get the parameters used to fit the corrector and thus include them in the report (#802). 
- Add NiMAREBase features to the Corrector base class
> Add NiMAREBase features to the Corrector base class

- nimare/io.py
> [FIX] allow analysis to have null points when converting from nimads to dataset

- setup.cfg
Closes #813 .
- include default.yml/defaul.tpl in the python package
> [FIX] include default.yml as part of nimare package

- nimare/diagnostics.py
Closes #838  .
- add function to catch index errors return False
-
> [FIX] handle index errors

- docs/api.rst
- examples/02_meta-analyses/08_plot_cbma_subtraction_conjunction.py
- nimare/tests/test_workflows.py
- nimare/workflows/__init__.py
- nimare/workflows/ale.py
- nimare/workflows/misc.py
- setup.cfg
Closes None.
- Add Conjunction Analysis Workflow.
> Add Conjunction Analysis Workflow

- nimare/meta/utils.py
- setup.cfg
Closes # .
- do not rely on features that require a newer version of numpy
-
> [FIX] bump min numpy/seaborn versions

- nimare/reports/base.py
- nimare/reports/figures.py
- setup.cfg
Closes None.
- Replace the custom code based on seaborn, which was producing strange results for specific data.
- Ridgeplot is more straightforward and interactive given that it is based on Plotly.
- Another improvement is the ability to set the color gradient along the horizontal axis, which helps compare the different distributions from the images.
> Fix ridgeline plot in IBMA report

- .github/workflows/testing.yml
> [FIX] update codecov

- setup.cfg
Closes # .
- makes this package compatible with python 3.12
-
> [MAINT] bump cognitiveatlas version

- examples/01_datasets/05_plot_nimads.py
- nimare/nimads.py
- nimare/tests/test_io.py
- nimare/tests/test_nimads.py
Closes #920
- implement many of the methods within the studyset class
> [ENH] implement methods and test the nimads methods
